### ISSUE TITLE
MacOS Icon

### ISSUE THREAD

**Issue by roaldarbol** [kochrt/timeline-maker#131]
The current transparent icon doesn't work very well in the Mac dock. I've made a quick edit, putting it on a white background:
I can upload the SVG as well. I'll upload it to https://macosicons.com/ as well. :-)

<img src="https://github.com/mark-when/markwhen/assets/25629697/543fa14c-33a1-4017-9968-c92221cfb3e9" width="512">

**Comment by kochrt** [comment]
I was just fiddling with the mac icon yesterday and could not figure out how to get it to look better in the dock! I think Chrome pulls the favicon instead of whatever is listed in the [app manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest), unfortunately, and I think(?) it makes sense for the favicon to have the transparent bg.

Half the reason I'm thinking about doing an electron app is so I can have an actually good-looking dock icon...

Do you know of other projects (PWAs) that have good macos dock icons?

Meanwhile thanks for making that!

**Comment by kochrt** [comment]
Might as well upload the svg, i might use it

**Comment by roaldarbol** [comment]
Haha, no worries! Personally, I prefer having the clean white background with rounded corners. But I'd be happy to help with making a few different versions if you have other ideas to test out - they can all go on [macosicons](https://macosicons.com/) no matter what anyways.

**Comment by roaldarbol** [comment]
Here's the SVG:
![markwhen](https://github.com/mark-when/markwhen/assets/25629697/33a7d933-40b3-4a6c-9ed0-91af2966f9ee)

**Comment by roaldarbol** [comment]
In case others want to change their icon, here's how to: https://macosicons.com/how-to#/how-to
